stages:
  - build
  - test
  - build-docker
  - deploy

build:
  image: rust
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustup update nightly
    - rustup default nightly
  script:
    - cargo build
  artifacts:
    paths:
      - target/
  only:
    - branches
    - tags
    - api
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests

build-docs:
  image: rust
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustup update nightly
    - rustup default nightly
  script:
    - cargo doc
  artifacts:
    paths:
      - target/
  only:
    - branches
    - tags
    - api
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests

test:
  image: rust
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustup update nightly
    - rustup default nightly
  script:
    - cargo test
  artifacts:
    paths:
      - target/
  only:
    - branches
    - tags
    - api
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests

build-docker-server:
  stage: build-docker
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE: "$CI_REGISTRY_IMAGE/server"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest -f docker/server/Dockerfile .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
    - if [ "$CI_COMMIT_BRANCH" -eq "master" ]; then docker tag "$IMAGE:$CI_COMMIT_SHA" "$IMAGE:$CI_COMMIT_BRANCH"; docker push "$IMAGE:$CI_COMMIT_BRANCH"; fi
  only:
    - branches
    - tags
    - api
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests

build-docker-importer:
  stage: build-docker
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE: "$CI_REGISTRY_IMAGE/importer"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest -f docker/import/Dockerfile .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:latest
    - if [ "$CI_COMMIT_BRANCH" -eq "master" ]; then docker tag "$IMAGE:$CI_COMMIT_SHA" "$IMAGE:$CI_COMMIT_BRANCH"; docker push "$IMAGE:$CI_COMMIT_BRANCH"; fi
  only:
    - branches
    - tags
    - api
    - pipelines
    - schedules
    - triggers
    - web
    - merge_requests

deploy:
  stage: deploy
  image: ubuntu
  before_script:
    - apt update
    - apt install -y ssh python3 python3-pip
    - pip3 install ansible
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 0700 ~/.ssh
    - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-add -L
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ansible-playbook -i inventory.conf playbooks/00_main.yml
  only:
    - master
    - schedules
    - web
