stages:
  - build
  - merge
  
pages:
  stage: build
  image: node:10.15.3
  cache:
    paths:
      - node_modules/
  before_script:
    - yarn install
    - yarn global add hexo-cli
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master

merge:
  stage: merge
  image: node:10.15.3
  cache:
    paths:
      - node_modules/
  before_script:
    - yarn install
    - yarn global add hexo-cli
  script:
    - yarn audit
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - merge_requests
