stages:
  - docker_base
  - docker
  - check
  - test
  - build
  - deploy

include:
  - local: '/.gitlab-ci-docker.yml'
  - local: '/.gitlab-ci-rust-validation.yml'
  - local: '/.gitlab-ci-rust-build.yml'
  - local: '/.gitlab-ci-deploy.yml'