stages:
  - build
  - test
  - build-docker
  - deploy

build:
  image: rust
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustup update nightly
    - rustup default nightly
  script:
    - cargo build
  artifacts:
    paths:
      - target/

build-docs:
  image: rust
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustup update nightly
    - rustup default nightly
  script:
    - cargo doc
  artifacts:
    paths:
      - target/

test:
  image: rust
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - rustup update nightly
    - rustup default nightly
  script:
    - cargo test
  artifacts:
    paths:
      - target/

build-docker-server:
  stage: build-docker
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE: "$CI_REGISTRY_IMAGE/server"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest --tag $IMAGE:$CI_COMMIT_BRANCH -f docker/server/Dockerfile .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:$CI_COMMIT_BRANCH
    - docker push $IMAGE:latest

build-docker-importer:
  stage: build-docker
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE: "$CI_REGISTRY_IMAGE/importer"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest --tag $IMAGE:$CI_COMMIT_BRANCH -f docker/import/Dockerfile .
    - docker push $IMAGE:$CI_COMMIT_SHA
    - docker push $IMAGE:$CI_COMMIT_BRANCH
    - docker push $IMAGE:latest

deploy:
  stage: deploy
  image: ansible/ansible
  before_script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 0700 ~/.ssh
    - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh-add -L
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ansible-playbook -i inventory.conf playbooks/00_main.yml
  only:
    - master
