image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script: npm install && npm run deploy
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedules
    - triggers
    - web
    - merge_requests
    - chats

.deploy_template: &deploy_definition
  before_script:
  # Create directories and give write permissions to it
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Store public and private key
  - echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  # Make sure both keys DON'T end with a new line
  - sed  '/^$/d' ~/.ssh/id_rsa > ~/.ssh/id_rsa
  - sed  '/^$/d' ~/.ssh/id_rsa.pub > ~/.ssh/id_rsa.pub
  # Set read permission for private key
  - chmod 600 ~/.ssh/id_rsa
  # Invoke ssh-agent and add private key
  - eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
  # Add deploy domain to known hosts
  - ssh-keyscan -H 'raw.sakul6499.de' >> ~/.ssh/known_hosts
  # [Probably optional:] Set git credentials
  - git config --global user.email "webmaster@sakul6499.de"
  - git config --global user.name "webmaster"

deploy_preview:
  stage: deploy
  <<: *deploy_definition
  script: rsync -avrPtzu -e "ssh -p 4753" . webmaster@raw.sakul6499.de:/srv/http/preview.sakul6499.de/
  environment:
    name: preview
    url: https://preview.sakul6499.de
  except:
  - master

deploy_production:
  stage: deploy
  <<: *deploy_definition
  script: rsync -avrPtzu -e "ssh -p 4753" . webmaster@raw.sakul6499.de:/srv/http/sakul6499.de/
  environment:
    name: production
    url: https://sakul6499.de
  when: manual
  only:
  - master