image: node:10.15.3

cache:
  paths:
    - node_modules/

before_script:
  - yarn install
  - yarn global add hexo-cli

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master
