image: node:10-alpine # use nodejs v10 LTS
cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - cd themes/aether && npm install
  - cd ../.. && npm install

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master