stages:
  - build
  
pages:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - cd themes/aether && npm install
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

merge:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - cd themes/aether && npm install
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - merge_requests