image: rust

before_script:
  - rustup update nightly
  - rustup default nightly

build:
  script:
    - cargo build
  artifacts:
    paths:
      - target/

build-docs:
  script:
    - cargo docs
  artifacts:
    paths:
      - target/

test:
  script:
    - cargo test
  artifacts:
    paths:
      - target/
