deploy_staging:
  stage: deploy
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
  dependencies:
    - build_lnx_gnueabihf_stable_release
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
    - ssh -p22 deploy@raw.sakul6499.de "mkdir -p /srv/website/staging/tmp"
    - rsync -rav -e ssh --exclude='.git/*' --exclude='.gitlab-ci.yml' --delete-excluded artifacts/* deploy@raw.sakul6499.de:/srv/website/staging/tmp
    - ssh -p22 deploy@raw.sakul6499.de "if [ -d '/srv/website/staging/current' ]; then mv /srv/website/staging/current /srv/website/staging/old; fi && mv /srv/website/staging/tmp /srv/website/staging/current"
    - ssh -p22 deploy@raw.sakul6499.de "rm -rf /srv/website/staging/old"
    - ssh -p22 deploy@raw.sakul6499.de "sudo systemctl restart staging-server"
  environment:
    name: staging
    url: https://staging.sakul6499.de
  only:
    - staging

deploy_master:
  stage: deploy
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
  dependencies:
    - build_lnx_gnueabihf_stable_release
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
    - ssh -p22 deploy@raw.sakul6499.de "mkdir -p /srv/website/master/tmp"
    - rsync -rav -e ssh --exclude='.git/*' --exclude='.gitlab-ci.yml' --delete-excluded artifacts/* deploy@raw.sakul6499.de:/srv/website/master/tmp
    - ssh -p22 deploy@raw.sakul6499.de "if [ -d '/srv/website/master/current' ]; then mv /srv/website/master/current /srv/website/master/old; fi && mv /srv/website/master/tmp /srv/website/master/current"
    - ssh -p22 deploy@raw.sakul6499.de "rm -rf /srv/website/master/old"
    - ssh -p22 deploy@raw.sakul6499.de "sudo systemctl restart master-server"
  environment:
    name: master
    url: https://sakul6499.de
  only:
    - master