build_lnx_x86_64_stable_debug:
    stage: build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/lnx_x86_64_stable
    before_script:
        - if [ ! -d "logs" ]; then mkdir -p logs; fi
    script:
        - cargo +stable build 2>&1 | tee logs/build_stable_debug
    artifacts:
        untracked: true
        when: always

build_lnx_x86_64_stable_release:
    stage: build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/lnx_x86_64_stable
    before_script:
        - if [ ! -d "logs" ]; then mkdir -p logs; fi
    script:
        - cargo +stable build --release 2>&1 | tee logs/build_stable_release
    artifacts:
        untracked: true
        when: always

build_lnx_x86_64_beta_debug:
    stage: build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/lnx_x86_64_beta
    before_script:
        - if [ ! -d "logs" ]; then mkdir -p logs; fi
    script:
        - cargo +beta build 2>&1 | tee logs/build_beta_debug
    artifacts:
        untracked: true
        when: always

build_lnx_x86_64_beta_release:
    stage: build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/lnx_x86_64_beta
    before_script:
        - if [ ! -d "logs" ]; then mkdir -p logs; fi
    script:
        - cargo +beta build --release 2>&1 | tee logs/build_beta_release
    artifacts:
        untracked: true
        when: always

build_lnx_x86_64_nightly_debug:
    stage: build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/lnx_x86_64_nightly
    before_script:
        - if [ ! -d "logs" ]; then mkdir -p logs; fi
    script:
        - cargo +nightly build 2>&1 | tee logs/build_debug_vulkan
    artifacts:
        untracked: true
        when: always

build_lnx_x86_64_nightly_release:
    stage: build
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/lnx_x86_64_nightly
    before_script:
        - if [ ! -d "logs" ]; then mkdir -p logs; fi
    script:
        - cargo +nightly build --release 2>&1 | tee logs/build_release_vulkan
    artifacts:
        untracked: true
        when: always