stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/docker-arch/rust/wasm-stable:latest
  script:
    - ./build.sh
  artifacts:
    paths:
        - out/

deploy_staging:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y ssh
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
    - ssh -p22 deploy@raw.sakul6499.de "mkdir -p /srv/website/staging/tmp"
    - rsync -rav -e ssh --exclude='.git/*' --exclude='.gitlab-ci.yml' --delete-excluded out/* nginx.conf mime.types deploy@raw.sakul6499.de:/srv/website/staging/tmp
    - ssh -p22 deploy@raw.sakul6499.de "if [ -d '/srv/website/staging/current' ]; then mv /srv/website/staging/current /srv/website/staging/old; fi && mv /srv/website/staging/tmp /srv/website/staging/current"
    - ssh -p22 deploy@raw.sakul6499.de "rm -rf /srv/website/staging/old"
    - ssh -p22 deploy@raw.sakul6499.de "docker rm -f web_staging && docker run -d --name web_staging -p 80:80 -v /srv/website/staging/current:/usr/share/nginx/html:ro -v /srv/website/staging/current/nginx.conf:/etc/nginx/nginx.conf:ro nginx"
  environment:
    name: staging
    url: https://staging.sakul6499.de
  only:
    - staging
  needs:
    - build