stages:
  - build
  
build:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - yarn global add hexo-cli
  script:
    - cd themes/aether
    - yarn install
    - cd ../..
    - yarn install
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - master

merge:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules/
  before_script:
    - yarn global add hexo-cli
  script:
    - cd themes/aether
    - yarn install
    - cd ../..
    - yarn install
    - hexo generate
  artifacts:
    paths:
      - public
  only:
    - merge_requests