stages:
  - docker
  - build
  - deploy

docker_image:
  stage: docker
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -f Dockerfile -t $IMAGE_NAME -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  only:
    changes:
      - "Dockerfile"

build:
  stage: build
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  script:
    - npm ci
    - npm r build
  artifacts:
    paths:
        - build/

deploy_staging:
  stage: deploy
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
    - ssh deploy@raw.sakul6499.de "mkdir -p /srv/staging/tmp"
    - rsync -rav -e ssh build/* nginx.conf deploy@raw.sakul6499.de:/srv/staging/tmp
    - ssh deploy@raw.sakul6499.de "if [ -d '/srv/staging/current' ]; then mv /srv/staging/current /srv/staging/old; fi && mv /srv/staging/tmp /srv/staging/current"
    - ssh deploy@raw.sakul6499.de "rm -rf /srv/staging/old"
    - ssh deploy@raw.sakul6499.de 'docker stop web && docker rm -vf web; docker run -d --name web -p 80:80 -v /srv/staging/current:/usr/share/nginx/html/staging:ro -v /srv/master/current:/usr/share/nginx/html/master:ro -v /srv/staging/current/nginx.conf:/etc/nginx/nginx.conf:ro nginx'
  environment:
    name: staging
    url: https://staging.sakul6499.de
  only:
    - staging
  needs:
    - build

deploy_master:
  stage: deploy
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
  script:
    - ssh deploy@raw.sakul6499.de "mkdir -p /srv/master/tmp"
    - rsync -rav -e ssh build/* nginx.conf deploy@raw.sakul6499.de:/srv/master/tmp
    - ssh deploy@raw.sakul6499.de "if [ -d '/srv/master/current' ]; then mv /srv/master/current /srv/master/old; fi && mv /srv/master/tmp /srv/master/current"
    - ssh deploy@raw.sakul6499.de "rm -rf /srv/master/old"
    - ssh deploy@raw.sakul6499.de 'docker stop web && docker rm -vf web; docker run -d --name web -p 80:80 -v /srv/staging/current:/usr/share/nginx/html/staging:ro -v /srv/master/current:/usr/share/nginx/html/master:ro -v /srv/master/current/nginx.conf:/etc/nginx/nginx.conf:ro nginx'
  environment:
    name: master
    url: https://sakul6499.de
  only:
    - master
  needs:
    - build