stages:
  - build
  - build_remote
  - deploy

build_frontend:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - sh make_docker_files.sh
    - docker build -t sakul6499de_frontend -f frontend/Dockerfile.out frontend
    - docker tag sakul6499de_frontend registry.gitlab.com/sakul6499.de/sakul6499.de/frontend:x86
    - docker push registry.gitlab.com/sakul6499.de/sakul6499.de/frontend:x86
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests

build_backend:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - sh make_docker_files.sh
    - docker build -t sakul6499de_backend -f backend/Dockerfile.out backend
    - docker tag sakul6499de_backend registry.gitlab.com/sakul6499.de/sakul6499.de/backend:x86
    - docker push registry.gitlab.com/sakul6499.de/sakul6499.de/backend:x86
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests

build_mongo-seeder:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - sh make_docker_files.sh
    - docker build -t sakul6499de_mongo-seeder -f docker/mongo-seeder/Dockerfile.out docker/mongo-seeder
    - docker tag sakul6499de_mongo-seeder registry.gitlab.com/sakul6499.de/sakul6499.de/mongo-seeder:x86
    - docker push registry.gitlab.com/sakul6499.de/sakul6499.de/mongo-seeder:x86
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests

build_remote:
  stage: build_remote
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y ssh rsync
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRIVATE_KEY")
  script:
    - ssh deploy@raw.sakul6499.de "rm -rf website; mkdir -p website"
    - rsync -ravz -I -O --no-perms --no-owner --no-group --delete -e ssh * deploy@raw.sakul6499.de:/home/deploy/website/
    - ssh deploy@raw.sakul6499.de "cd website && bash make_docker_files.sh"
    - ssh deploy@raw.sakul6499.de "cd website && docker build -t sakul6499de_frontend -f frontend/Dockerfile.out frontend"
    - ssh deploy@raw.sakul6499.de "cd website && docker build -t sakul6499de_backend -f backend/Dockerfile.out backend"
    - ssh deploy@raw.sakul6499.de "cd website && docker build -t sakul6499de_mongo-seeder -f docker/mongo-seeder/Dockerfile.out docker/mongo-seeder"
    - ssh deploy@raw.sakul6499.de "cd website && docker tag sakul6499de_frontend registry.gitlab.com/sakul6499.de/sakul6499.de/frontend:arm"
    - ssh deploy@raw.sakul6499.de "cd website && docker tag sakul6499de_backend registry.gitlab.com/sakul6499.de/sakul6499.de/backend:arm"
    - ssh deploy@raw.sakul6499.de "cd website && docker tag sakul6499de_mongo-seeder registry.gitlab.com/sakul6499.de/sakul6499.de/mongo-seeder:arm"
    - ssh deploy@raw.sakul6499.de "cd website && docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker push registry.gitlab.com/sakul6499.de/sakul6499.de/frontend:arm"
    - ssh deploy@raw.sakul6499.de "cd website && docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker push registry.gitlab.com/sakul6499.de/sakul6499.de/backend:arm"
    - ssh deploy@raw.sakul6499.de "cd website && docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY && docker push registry.gitlab.com/sakul6499.de/sakul6499.de/mongo-seeder:arm"
  only:
      - master

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y ssh rsync
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRIVATE_KEY")
  script:
    - ssh deploy@raw.sakul6499.de "rm -rf website; mkdir -p website"
    - rsync -ravz -I -O --no-perms --no-owner --no-group --delete -e ssh * deploy@raw.sakul6499.de:/home/deploy/website/
    - ssh deploy@raw.sakul6499.de "cd website && bash make_docker_files.sh deploy"
    - ssh deploy@raw.sakul6499.de "cd website && docker stack rm website && docker stack deploy --compose-file docker-compose.yml.out website"
  environment:
    name: master
    url: https://sakul6499.de
  only:
    - master