image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script: npm install && npm run deploy
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedules
    - triggers
    - web
    - merge_requests
    - chats

.deploy_template: &deploy_definition
  before_script:
  # Create directories and give write permissions to it
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Store public and private key
  - echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/webmaster.pub
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/webmaster
  # Set permission for keys
  - chmod 600 ~/.ssh/webmaster
  - chmod 644 ~/.ssh/webmaster.pub
  # Invoke ssh-agent and add private key
  - eval $(ssh-agent -s) && ssh-add ~/.ssh/webmaster
  # Add deploy domain to known hosts
  - ssh-keyscan -H 'raw.sakul6499.de' >> ~/.ssh/known_hosts
  # [Probably optional:] Set git credentials
  - git config --global user.email "webmaster@sakul6499.de"
  - git config --global user.name "webmaster"
  # Install rsync
  - apt-get update -y && apt-get install -y rsync

deploy_preview:
  stage: deploy
  <<: *deploy_definition
  script: 
  # Clean directory
   - ssh -o StrictHostKeyChecking=No webmaster@raw.sakul6499.de -p 4753 'rm -rf /srv/http/preview.sakul6499.de/*'
  # Upload current version
   - rsync -avrPzuh --delete -e "ssh -p 4753" . webmaster@raw.sakul6499.de:/srv/http/preview.sakul6499.de/
  environment:
    name: preview
    url: https://preview.sakul6499.de
  except:
  - master

deploy_production:
  stage: deploy
  <<: *deploy_definition
  script: 
  # Clean directory
   - ssh -o StrictHostKeyChecking=No webmaster@raw.sakul6499.de -p 4753 'rm -rf /srv/http/sakul6499.de/*'
  # Upload current version
   - rsync -avrPzuh --delete -e "ssh -p 4753" . webmaster@raw.sakul6499.de:/srv/http/sakul6499.de/
  environment:
    name: production
    url: https://sakul6499.de
  when: manual
  only:
  - master