image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script: npm install && npm run deploy
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedules
    - triggers
    - web
    - merge_requests
    - chats