image: node:latest

stages:
  - build

build:
  stage: build
  script: ./build.sh
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedules
    - triggers
    - web
    - merge_requests
    - chats