stages:
  - build
  - build_remote
  - deploy

build_frontend:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - ./make_docker_files.sh x86
    - docker-compose -f docker-compose.yml.out build frontend
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests

build_backend:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - ./make_docker_files.sh x86
    - docker-compose -f docker-compose.yml.out build backend
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests

build_mongo-seeder:
  stage: build
  image: docker/compose
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - ./make_docker_files.sh x86
    - docker-compose -f docker-compose.yml.out build mongo-seeder
  only:
    - branches
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests

build_remote:
  stage: build_remote
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y ssh rsync
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRIVATE_KEY")
  script:
    - ./make_docker_files.sh arm
    - ssh deploy@raw.sakul6499.de "rm -rf website; mkdir -p website"
    - rsync -ravz -I -O --no-perms --no-owner --no-group --delete -e ssh * deploy@raw.sakul6499.de:/home/deploy/website/
    - ssh deploy@raw.sakul6499.de "cd website; docker-compose build && docker-compose push"
  only:
      - master

    # build_remote:
    #   stage: build_remote
    #   image: ubuntu
    #   before_script:
    #     - mkdir -p ~/.ssh
    #     - eval $(ssh-agent -s)
    #     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    #     - ssh-add <(echo "$PRIVATE_KEY")
    #   script:
    #     - ssh deploy@raw.sakul6499.de "rm -rf website; mkdir -p website"
    #     - rsync -ravz -I -O --no-perms --no-owner --no-group --delete -e ssh * deploy@raw.sakul6499.de:/home/deploy/website/
    #     - ssh deploy@raw.sakul6499.de "cd website; docker-compose build && docker-compose push"
    #   environment:
    #     name: master
    #     url: https://sakul6499.de
    #   only:
    #     - master