image: rust

build:
  script:
    - cargo build
  artifacts:
    paths:
      - target/

build-docs:
  script:
    - cargo docs
  artifacts:
    paths:
      - target/

test:
  script:
    - cargo test
  artifacts:
    paths:
      - target/
