stages:
  - docker
  - build
  - deploy

docker_build_image:
  stage: docker
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -f Dockerfile -t $IMAGE_NAME -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
  only:
    changes:
      - "build.docker"

build:
  stage: build
  image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  script:
    - yarn install
    - yarn build
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
  only:
    - api
    - pipelines
    - pushes
    - schedule
    - triggers
    - web
    - merge_requests
