version: '3'
services:
    mongodb:
        image: @MONGODB@
        command: mongod
        ports:
            - 27017:27017
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.labels.name==node2

    mongo-seeder:
        @MONGO_SEEDER@
        links:
            - mongodb
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.labels.name==node2

    backend:
        @BACKEND@
        links:
            - mongodb
        ports:
            - 4001:8081
        deploy:
            replicas: 1
            placement:
                constraints: 
                    - node.labels.name==node1

    frontend:
        @FRONTEND@
        links:
            - backend
        ports:
            - 4000:80
        deploy:
            replicas: 3
            placement:
                constraints: 
                    - node.labels.name!=homelab
