version: '3'
services:
    mongodb:
        image: mongo
        command: mongod
        ports:
            - 27017:27017

    mongo-seeder:
        build: docker/mongo-seeder/.
        links:
            - mongodb

    backend:
        build: backend/.
        links:
            - mongodb
        ports:
            - 8081:8081

    frontend:
        build: frontend/.
        links:
            - backend
        ports:
            - 8080:80