version: '3'
services:
    mongodb:
        image: mongo
        command: mongod
        ports:
            - 27017:27017
        deploy:
            replicas: 1
            placement:
                constraints: [node == homelab]

    mongo-seeder:
        build: docker/mongo-seeder/.
        links:
            - mongodb
        deploy:
            replicas: 1
            placement:
                constraints: [node == homelab]

    backend:
        build: backend/.
        links:
            - mongodb
        ports:
            - 8081:8081
        deploy:
            replicas: 1

    frontend:
        build: frontend/.
        links:
            - backend
        ports:
            - 8080:80
        deploy:
            mode: global