version: '3'
services:
    mongodb:
        image: mongo
        command: mongod
        ports:
            - 27017:27017

    mongo_seed:
        build: docker/mongo-seed/.
        links:
            - mongodb

    backend:
        build: backend/.
        links:
            - mongodb
        ports:
            - 8080:8080