version: '3'
services:
    mongodb:
        image: @MONGODB@
        command: mongod
        ports:
            - 27017:27017
        deploy:
            replicas: 1
            placement:
                constraints: [node == homelab]

    mongo-seeder:
        build:
            context: docker/mongo-seeder
            dockerfile: Dockerfile.out
        links:
            - mongodb
        deploy:
            replicas: 1
            placement:
                constraints: [node == homelab]

    backend:
        build:
            context: backend
            dockerfile: Dockerfile.out
        links:
            - mongodb
        ports:
            - 8081:8081
        deploy:
            replicas: 1

    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile.out
        links:
            - backend
        ports:
            - 8080:80
        deploy:
            mode: global