stages:
  - build
  - trigger

build:
  stage: build
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVE: overlay2
    MASTER_REGISTRY: registry.gitlab.com/sakul6499.de/sakul6499.de
    MASTER_REGISTRY_IMAGE: $MASTER_REGISTRY/frontend:x86
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u me@sakul6499.de -p $MASTER_CI_JOB_TOKEN $MASTER_REGISTRY
  script:
    - docker build -t $MASTER_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE .    
    - docker push $MASTER_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
  only:
    - schedule
    - web
    - merge_requests

trigger_root:
  stage: trigger
  trigger: sakul6499.de/website
