[package]
name = "import"
version = "0.1.0"
authors = ["@Sakul6499 | Lukas Weber <me@sakul6499.de>"]
edition = "2018"
publish = false

[dependencies]
data = { path = "../data" }
walkdir = "2"
dotenv = "0.15"
