---
- name: Ping server
  become: true
  become_user: root
  hosts: aether
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ping All Servers
      action: ping
    - debug: msg="Success"
