---
- name: Install dependencies
  become: true
  become_user: root
  hosts: aether
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Docker
      apt:
        name: docker
        state: latest

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: latest

    - name: Install Python3
      apt:
        name: python3
        state: latest

    - name: Install Python3 PIP
      apt:
        name: python3-pip
        state: latest

    - name: Install Docker Python API
      pip:
        executable: pip3
        name: docker
        state: latest
