---
- name: Docker
  become: true
  become_user: root
  hosts: aether
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: DB container
      docker_container:
        name: website_db
        image: postgres
        restart: yes
        recreate: yes
        pull: yes
        state: started
        env:
          POSTGRES_PASSWORD: postgres
    - name: Wait for PostgreSQL to fully start-up
      wait_for:
        timeout: 30
      delegate_to: localhost
    - name: Importer container
      docker_container:
        name: website_importer
        image: registry.gitlab.com/sakul6499_de/sakul6499_de.gitlab.io/importer:master
        restart: yes
        recreate: yes
        pull: yes
        state: started
        env:
          POSTS_PATH: "/posts"
          DATABASE_URL: "postgres://postgres:postgres@website_db:5432/postgres"
        links:
          - website_db
    - name: Server container
      docker_container:
        name: website_server
        image: registry.gitlab.com/sakul6499_de/sakul6499_de.gitlab.io/server:master
        restart: yes
        recreate: yes
        pull: yes
        state: started
        env:
          TEMPLATE_PATH: "/template"
          STATIC_PATH: "/static"
          DATABASE_URL: "postgres://postgres:postgres@website_db:5432/postgres"
          ROCKET_ENV: "production"
        ports:
          - "8000:8000"
        links:
          - website_db
