# Links in NavBar
menu:
  Home: /
  About: /about

# Content
excerpt_link: Read More

# Enabled widgets
widgets:
  about: true
  tags: true
  search: true

# Favicon
favicon: /favicon.ico

# SASS to CSS compilation
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Disqus Comments Shortname
disqus_shortname: sakul6499

# Google Analytics
google_analytics: UA-160626331-1

# Profile links
profile:
  gitea: https://git.sakul6499.de/
  gitlab: https://gitlab.com/Sakul6499
  github: https://github.com/Sakul6499
  bitbucket: https://bitbucket.org/%7Be556a531-5d5f-4ab9-a76d-bfc3043af83f%7D/
  linkedin: https://www.linkedin.com/in/lukaswebersakul6499
  keybase: https://keybase.io/sakul6499