# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
  about: This blog is a test ... BLA
  tags: true
  search: true

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Favicon
favicon: /favicon.png

# SASS to CSS compilation
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Disqus Comments Shortname
disqus_shortname: sakul6499

# Google Analytics
google_analytics: UA-160626331-1

# Search
search:
  path: search.xml
  field: post
  content: true

profile:
  gitlab: https://gitlab.com/Sakul6499
  github: https://github.com/Sakul6499
  bitbucket: https://bitbucket.org/%7Be556a531-5d5f-4ab9-a76d-bfc3043af83f%7D/
  linkedin: https://www.linkedin.com/in/lukaswebersakul6499