[package]
name = "post_seeder"
version = "0.1.0"
authors = ["Lukas Weber <me@sakul6499.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "^2"
json = "^0"